[package]
name = "humpty"
version = "0.1.0"
edition = "2021"
authors = ["Alexander Schuetz <aschuetz@protonmail.com>", "Kevin Nakamura <grinkers@grinkers.net>"]
license = "MIT"
homepage = "https://github.com/Grinkers/humpty"
repository = "https://github.com/Grinkers/humpty"
readme = "README.md"
description = "A Low-Latency Web Server."
keywords = ["http", "server", "http-server"]
categories = ["web-programming::http-server", "network-programming"]

[dependencies]
rand = "0.8.5"
log = { version = "^0.4.22", optional = true }
backtrace = { version = "0.3.74", optional = true}

[features]
default = []

[lints.rust]
future-incompatible = "warn"
rust_2018_idioms = { level = "warn", priority = -1 }
unsafe_code = "deny"
