[package]
name = "humpty"
version = "0.1.0"
edition = "2021"
authors = ["Alexander Schuetz <aschuetz@protonmail.com>", "Kevin Nakamura <grinkers@grinkers.net>"]
license = "MIT"
homepage = "https://github.com/Grinkers/humpty"
repository = "https://github.com/Grinkers/humpty"
readme = "README.md"
description = "A Low-Latency Web Server."
keywords = ["http", "server", "http-server"]
categories = ["web-programming::http-server", "network-programming"]

[dependencies]
backtrace = { version = "0.3.74", optional = true}
constutils = { path = "constutils" }
getrandom = { version = "0.2", optional = true }
log = { version = "^0.4.22", optional = true }
unowned-buf = "0.1.2"
urlencoding = "2.1.3"
regex = "1.11.1"
sha1 = "0.10.6"
base64 = "0.22.1"


## SSL
rustls = { version = "0.23.18", optional = true }
rust-tls-duplex-stream = { version = "0.1.1", optional = true }

[target.'cfg(unix)'.dependencies]
libc = { version = "*", optional = true }

[dev-dependencies]
rustls-pemfile = "2.2.0"
rustls = "0.23.18"
colog = "1.3.0"

[features]
default = []
random_id = ["getrandom"]
ssl = ["rust-tls-duplex-stream", "rustls"]
extras = ["libc"]

[lints.rust]
future-incompatible = "warn"
rust_2018_idioms = { level = "warn", priority = -1 }
unsafe_code = "deny"

[[example]]
name = "basic"
path = "examples/basic.rs"
required-features = ["log", "extras"]

[[example]]
name = "shutdown"
path = "examples/shutdown.rs"
required-features = ["extras"]

[[example]]
name = "shutdown2"
path = "examples/shutdown2.rs"
required-features = ["extras", "log"]

[[example]]
name = "ssl"
path = "examples/ssl.rs"
required-features = ["ssl"]

[[example]]
name = "static-content"
path = "examples/static-content.rs"
required-features = ["extras"]

[[example]]
name = "wildcard"
path = "examples/wildcard.rs"
required-features = ["extras"]

[[example]]
name = "websocket"
path = "examples/websocket.rs"
required-features = ["extras", "log"]

[[example]]
name = "unix"
path = "examples/unix.rs"
required-features = ["extras", "log"]